import { Photo } from "@/types/photos";

export const photos: Photo[] = [
    {
      id: 1,
      src: "/photos/amazon badge.jpeg",
      title: "Amazon Badge",
      date: "Summer 2024",
      location: "Seattle, WA",
    },
    {
      id: 2,
      src: "/photos/reinvent aws orange room.jpeg",
      title: "AWS re:Invent Orange Room",
      date: "Summer 2024",
      location: "Seattle, WA",
    },
    {
      id: 3,
      src: "/photos/boston skyline.jpeg",
      title: "Boston Skyline",
      date: "Fall 2023",
      location: "Boston, MA",
    },
    {
      id: 4,
      src: "/photos/charles river frozen.jpeg",
      title: "Frozen Charles River",
      date: "Winter 2025",
      location: "Cambridge, MA",
    },
    {
      id: 5,
      src: "/photos/golden gate bridge.jpeg",
      title: "Golden Gate Bridge",
      date: "Summer 2025",
      location: "San Francisco, CA",
    },
    {
      id: 6,
      src: "/photos/grill and chill.jpeg",
      title: "Grill and Chill",
      date: "Spring 2025",
      location: "MIT Campus",
    },
    {
      id: 7,
      src: "/photos/madison square garden watch party.jpeg",
      title: "MSG Watch Party",
      date: "Summer 2025",
      location: "New York, NY",
    },
    {
      id: 8,
      src: "/photos/massive chipotle bowl.jpeg",
      title: "Massive Chipotle Bowl",
      date: "Summer 2025",
      location: "Seattle, WA",
    },
    {
      id: 9,
      src: "/photos/me and justin.jpeg",
      title: "With Justin",
      date: "Spring 2025",
      location: "MIT Campus",
    },
    {
      id: 10,
      src: "/photos/me and shaun BT.jpeg",
      title: "With Shaun at BT",
      date: "Fall 2024",
      location: "Boston, MA",
    },
    {
      id: 11,
      src: "/photos/me sne shaun stanford.jpeg",
      title: "Stanford Visit with Shaun",
      date: "Summer 2025",
      location: "Stanford, CA",
    },
    {
      id: 13,
      src: "/photos/mit main campus sunset.jpeg",
      title: "MIT Main Campus Sunset",
      date: "Spring 2024",
      location: "Cambridge, MA",
    },
    {
      id: 14,
      src: "/photos/mit stata center.jpeg",
      title: "MIT Stata Center",
      date: "Spring 2025",
      location: "Cambridge, MA",
    },
    {
      id: 15,
      src: "/photos/mount rainier snow.jpeg",
      title: "Mount Rainier Snow",
      date: "Summer 2025",
      location: "Mount Rainier, WA",
    },
    {
      id: 16,
      src: "/photos/mount rainier view.jpeg",
      title: "Mount Rainier View",
      date: "Summer 2025",
      location: "Mount Rainier, WA",
    },
    {
      id: 17,
      src: "/photos/my rings.jpeg",
      title: "My Rings",
      date: "Spring 2025",
      location: "MIT Campus",
    },
    {
      id: 18,
      src: "/photos/playa acai bowl.jpeg",
      title: "Playa Bowls Acai",
      date: "Summer 2025",
      location: "Boston, MA",
    },
    {
      id: 19,
      src: "/photos/rainy day chelsea.jpeg",
      title: "Rainy Day in Chelsea",
      date: "Winter 2025",
      location: "New York, NY",
    },
    {
      id: 20,
      src: "/photos/shahs halal.jpeg",
      title: "Shah's Halal Food",
      date: "Spring 2025",
      location: "Boston, MA",
    },
    {
      id: 21,
      src: "/photos/sophomore spring grill session.jpeg",
      title: "Sophomore Spring Grill Session",
      date: "Spring 2025",
      location: "MIT Campus",
    },
    {
      id: 22,
      src: "/photos/tacos chukis.jpeg",
      title: "Tacos Chukis",
      date: "Summer 2025",
      location: "Seattle, WA",
    },
  ];